### ISSUE TITLE
'%s' % time.time() -> '{}'.format(time.time())

### ISSUE THREAD

**Issue by mdornseif** [asottile/pyupgrade#110]
Currently ony tuples and dicts used in `%` format are converted to `.fortmat()` calls. Would be nice if single parameter non tuple percentformat Strings would be converted, too.

**Comment by merwok** [comment]
May I ask: Why use a format string when there is no formatting?
Isn’t it more direct to do `str(time.time())`

**Comment by asottile** [comment]
In a sad twist of fate, the same reason `%` formatting is considered "bad" is the same reason `pyupgrade` can't safely rewrite that.  That is, **without knowing the _type_ of a single-element format, it's not possible to know what the outcome will be**.

Consider the simplest case as follows:

```python
print('%s' % x)
```

if `x` is a scalar:

```pycon
>>> x = 1
>>> print('%s' % x)
1
```

Equivalent would be `print('{}'.format(x))`

if `x` is a 1-tuple

```pycon
>>> x = (1,)
>>> print('%s' % x)
1
```

Equivalent would be `print('{}'.format(*x))`

____

that said, there are currently a few cases that `pyupgrade` _could_ rewrite which it doesn't:

```python
'%s %s' % x  # `'{} {}'.format(*x)
'%(foo)s %(bar)s' % x  # '{foo} {bar}'.format(**x)
```

mostly just because it didn't get written in the first pass due to being ~slightly more complicated than the (already complicated) simple case

____

You can see a list of the currently intentionally avoided `%` format strings as part of the tests: https://github.com/asottile/pyupgrade/blob/cfa9ca23a626011376e2189af7ad6641387a4456/tests/pyupgrade_test.py#L559-L600

And a list of the "xfail, TODO" cases as part of the tests: https://github.com/asottile/pyupgrade/blob/cfa9ca23a626011376e2189af7ad6641387a4456/tests/pyupgrade_test.py#L643-L691

(though it looks like I didn't even consider the splatting formats there as above, woops!)

**Comment by merwok** [comment]
> without knowing the type of a single-element format, it's not possible to know what the outcome will be.

Are you alluding to the implicit unicode promotion?  (If so, using print instead of repr in examples doesn’t make it obvious :))

I have to say I don’t think a lot about Python 2 these days, and I don’t know what projects are targeted by this tool.

**Comment by asottile** [comment]
> > without knowing the type of a single-element format, it's not possible to know what the outcome will be.
> 
> Are you alluding to the implicit unicode promotion? (If so, using print instead of repr in examples doesn’t make it obvious :))
> 
> I have to say I don’t think a lot about Python 2 these days, and I don’t know what projects are targeted by this tool.

I'm referring to tuple-vs-not (I provided an example directly below demonstrating).  basically `'%s' % x` could be either `'{}'.format(x)` or `'{}'.format(*x)` and without knowing the type the tool can't pick one without being wrong sometimes

**Comment by merwok** [comment]
Right, I read too fast.

%-formatting also has the issue of operator precedence.

I wonder if 2to3 converts %-formats!  If not, it may be too hard to do mechanically.  Just like proper handling and testing of str vs unicode, I think many people have been manually migrating from % to format since Python 2.6, to avoid these problems later.

**Comment by asottile** [comment]
It doesn't -- therefore this tool :D

**Comment by asottile** [comment]
Closing since this is intentional
