### ISSUE TITLE
printf-formatting not converted when there is whitespace between string and % operator

### ISSUE THREAD

**Issue by mjpieters** [asottile/pyupgrade#209]
pyupgrade fails to detect printf formatting operations when there is no whitespace between the string and the operator:

```sh
$ echo "limitQuery = 'LIMIT %s,%s'% (limit, ll)" | pyupgrade -
limitQuery = 'LIMIT %s,%s'% (limit, ll)
``` 

If there is whitespace, the conversion is succesful:

```sh
$ echo "limitQuery = template % (limit, ll)" | pyupgrade -
limitQuery = template % (limit, ll)
```

**Comment by asottile** [comment]
this is one of the timid parts of pyupgrade, if your code is not well formatted to begin with it won't try to fix it for you

**Comment by mjpieters** [comment]
Luckily, it's not my code :-) I reported this [following a Stack Overflow question](https://stackoverflow.com/q/58271843/100297).

My advise to them is to use `black` first.

**Comment by asottile** [comment]
ahah!  I thought I recognized the name from somewhere -- I see you all the time on SO :)

pyupgrade may become less timid over time and documenting the various cases where it currently takes a shortcut (beyond just referring to the testsuite) would make the docs overwhelming unreadable heh

that said, I imagine a future where this particular case is handled -- just hasn't been implemented yet due to being very low priority

thanks again for the issue!
