### ISSUE TITLE
quoted annotations + `from __future__ import annotations`

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#255]
should remove the quotes

need to be careful of:
- `Literal['foo']`
- `Annotated` ([PEP 593](https://www.python.org/dev/peps/pep-0593/))

**Comment by asottile** [comment]
it would be cool if it could automated something like this as well, but this is understandably more difficult: https://github.com/pre-commit/pre-commit/pull/1318

it would need to identify:
- name was previously defined (and/or unconditionally imported)
- it is exactly a `Name` (maybe allow dotted name? would have to think more about that)

**Comment by henryiii** [comment]
Simply adding the `__future__` import would be useful, as it will be default in 3.10 and might even make code a tiny bit faster. But stripping quotes would be even better!

**Comment by asottile** [comment]
you could add the import with `reorder-python-imports --add-import 'from __future__ import annotations'` -- adding code isn't really in the spirit of pyupgrade though

**Comment by henryiii** [comment]
Didn’t know about that one!

**Comment by MarcoGorelli** [comment]
Hi @asottile ,

I wanted to give this a go. I made my own little package https://github.com/MarcoGorelli/no-string-hints which does this - is the logic of it on the right track? I couldn't find a way to do it that's as simple/elegant as the pyupgrade plugins because of the difficulty in telling if a node comes from `Literal` (i.e. shouldn't be de-quoted) or something else

and @henryiii - if you need to run this, it might be useful to you, it's been running in pandas for a couple of months now and so far nothing's exploded

**Comment by henryiii** [comment]
Bookmarked, thanks!!! I likely won't be running this much till next year, but I have a few packages that are 3.7+ or partially 3.7+ (internal scripts and such mostly are).

**Comment by asottile** [comment]
yeah the problem is there's *a lot* of edge cases in typing: `Literal`, `Annotated`, `cast`, `TypedDict`, `NamedTuple`, `TypeVar`, just to name a few -- I haven't started compiling a full list of them, though the `pyflakes` testsuite covers a lot of them

**Comment by MarcoGorelli** [comment]
I think the ones you'd opened are handled - in `dequote-annotations`, I'm just looking at:
- the `.annotation` attribute of `ast.FunctionDef` args
- the `.annotation` attribute of `ast.FunctionDef` returns
- `ast.AnnAssign` nodes

`cast` and `TypeVar` wouldn't be reached because `ast.Assign` isn't visited in the above. Indeed, they shouldn't be changed, so this is alright.

`NamedTuple` and `TypedDict` are taken care of by the visits to the `ast.AnnAssign` nodes. They should be changed, so this is alright.

What's the issue with `Annotated`? If used when assigning to a variable (e.g. `t = Annotated['MyClass', 'metadata']`) then it'll be ignored by the above logic, while if it's `t: Annotated['MyClass', 'metadata']` then it can be dequoted and it'll be taken care of by the visit to the `AnnAssign` node

---

Perhaps the easiest thing is if I just start working on a PR, doing that now

**Comment by asottile** [comment]
the problem is all of those constructs are type context sensitive and can contain strings that should not be replaced (similar to `Literal`) -- there's also things in mypy's extensions (the function arg stuff) that's problematic too

**Comment by henryiii** [comment]
For example, `t: Annotated['MyClass', 'metadata']` can become `t: Annotated[MyClass, 'metadata']` but not `t: Annotated[MyClass, metadata]`, right? (Haven't used Annoatated yet, but I think it attaches just arbitrary metadata, "metadata" in this case). Same for many of the others, Literal has to always keep the strings, etc.
