### ISSUE TITLE
upgrade list comprehension splat to generator expression splat

### ISSUE THREAD

**Issue by graingert** [asottile/pyupgrade#257]
`foo(*[fn(x) for x in items])` -> `foo(*(fn(x) for x in items))` for py >= 2.4

**Comment by graingert** [comment]
and the same with unpacking

```
foo, bar, baz = [fn(x) for x in items]
```

**Comment by asottile** [comment]
due to listcomp leak I think this can only safely be done for `--py3-plus`

**Comment by zyv** [comment]
Hmmm, is there any reason why #961 was locked as off-topic o_O ?

The ruff people removed the rule because evidence was presented in astral-sh/ruff#12754 that it actually made code much slower. I was wondering why pyupgrade wanted to keep it, but the conversation was disabled.

Is it just a matter of style, performance notwithstanding, or is there more to it?
