### ISSUE TITLE
Recursive pyupgrade option

### ISSUE THREAD

**Issue by dsaxton** [asottile/pyupgrade#339]
Very cool project @asottile! I was curious if there was a way to run pyupgrade on whole directories or projects, and if not whether this might be a helpful feature to add? For instance have `pyupgrade -r some_directory` run recursively on the directory, or even drop the `-r` and let the recursive part be implied?

Thanks for building this!

**Comment by asottile** [comment]
dupe #150 #46

**Comment by asottile** [comment]
`pre-commit run pyupgrade --all-files`

**Comment by saroad2** [comment]
> `pre-commit run pyupgrade --all-files` or shell globs `pyupgrade **/*.py`

I don't think that this is sufficient solution, because now you are forcing the user to use `pre-commit` instead of simply using Pyupgrade as a standalone tool.

For instance, I would love to add Pyupgrade as one of the default tools run by [Statue](https://github.com/saroad2/statue), but the absence of the ability to run on directories is the only thing preventing me from doing it.

As I've shown in #344 , Implementation of this ability is quite easy and I hope you reconsider.
