### ISSUE TITLE
Replace typing.List with list and others

### ISSUE THREAD

**Issue by verhovsky** [asottile/pyupgrade#343]
https://docs.python.org/3.9/whatsnew/3.9.html#pep-585-builtin-generic-types

Python 3.9 (and Python 3.7 if you do `from __future__ import annotations`) will let you write

```
from typing import List

def a(my_arg: List) -> List:
    return []
```

as

```python
def a(my_arg: list) -> list:
    return []
```

Same goes for `typing.Dict` and a bunch of others, see https://www.python.org/dev/peps/pep-0585/

**Comment by graingert** [comment]
it might be worth expanding this issue into a general modern `typing` syntax epic.

upgrading conditional typing imports for new python version, or do people want it conditional still because `typing` can be slow to import?

should pyupgrade be upgrading redundant forward-references, in presence of the `from __future__ import annotations`, redundant forward-references seems like it might be a [pylint's](https://github.com/PyCQA/pylint/issues/3874) or pyflakes responsibility

what about type comments into full fledged annotations: `v: # type: ...` into `v: ...`?
and how about use of third party typing shims: `v: attr.ib(type=...)` into  `v: ... = attr.ib()`?

**Comment by verhovsky** [comment]
> type comments into full fledged annotations

https://github.com/ilevkivskyi/com2ann/blob/master/src/com2ann.py does this.

**Comment by verhovsky** [comment]
This shouldn't be implemented until mypy supports it https://github.com/python/mypy/issues/7907

**Comment by asottile** [comment]
agreed 👍

**Comment by jdufresne** [comment]
Perhaps another example of the same idea, replace `typing.Text` with `str` for `--py3-plus`.

Example input:

```py
if False:
    from typing import Text


def f():
    # type: () -> Text
    return "hello"
```

Example diff:

```diff
--- before.py
+++ after.py
@@ -3,5 +3,5 @@
 
 
 def f():
-    # type: () -> Text
+    # type: () -> str
     return "hello"

```

**Comment by asottile** [comment]
via #371

**Comment by twoertwein** [comment]
> Same goes for `typing.Dict` and a bunch of others, see https://www.python.org/dev/peps/pep-0585/

Are there plans to also re-write `Dict`, `Tuple`, ... for python 3.9+?

**Comment by asottile** [comment]
@twoertwein it's already implemented

**Comment by twoertwein** [comment]
Thanks, I just noticed that :)

I expected that `pyupgrade --py39-plus **/*.py` would traverse folders but it doesn't, so I still saw a lot of `typing.Dict` and so on.

**Comment by asottile** [comment]
you probably need the right `shopt` to do that -- I think it's `globstar`?
