### ISSUE TITLE
Optional is being rewritten

### ISSUE THREAD

**Issue by henryiii** [asottile/pyupgrade#390]
The latest update has started rewriting:

```diff
from __future__ import annotations
- x: Optional[str]
+ x: str | None
```

I don't know if this is universally better. Optional reads a bit better if that's what you want - This is optionally a string, while the union does't really say so as clearly. And there is a [proposed importless syntax for Optional](https://www.python.org/dev/peps/pep-0645/), `str?`, which is already used in MyPy to format the output in some places.

I thought MyPy used to have a message customization for Optional as well, but it doesn't seem to anymore.

Rewriting `Union[str, None]` as `str | None` is great, but not `Optional[str]` as `str | None` is questionable and a bit of a mater of taste. If pyupgrade is smart enough to rewrite `str | None` as `str?` in the future if that PEP is accepted, that would help a bit. :)

**Comment by asottile** [comment]
time to read up on [PEP 604](https://www.python.org/dev/peps/pep-0604/)

**Comment by asottile** [comment]
by the way ["Optional" is a misnomer and doesn't mean optional, it means nullable](https://youtu.be/7XZYlDpSxOU?list=PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY)

**Comment by asottile** [comment]
`None` is the special case because `type(None)` makes no sense (there's only ever one instance of `None`)

and yeah if 645 happens there'll be another thing to rewrite here -- but I highly doubt it will because it requires adding a new unary postfix operator to the syntax of which I don't believe there are any in python today

**Comment by nyuszika7h** [comment]
> time to read up on [PEP 604](https://www.python.org/dev/peps/pep-0604/)

PEP 604 does not deprecate `Optional`, it just mentions it's *possible* to use `| None`, but does not explicitly recommend it over the alternative. I'm not suggesting disabling this rewrite entirely, but it would be nice to have an option, because for me `X | Y` is unambiguously better than `Union[X, Y]` but `X | None` over `Optional[X]` is questionable. IMO readability is more important than arguing over the semantics of "Optional is ambiguous". A lot of things can be ambiguous to inexperienced programmers, this is not really the place to fight that.

**Comment by asottile** [comment]
nobody asked
