### ISSUE TITLE
Run on a file or directory

### ISSUE THREAD

**Issue by hugovk** [asottile/pyupgrade#40]
Thanks for this handy tool!

It would be nice to be able to run pyupgrade on a directory, and have it process all .py files in that directory and subdirectories.

For example:
```sh
pyupgrade .
```

This would be similar to other tools like [Flake8](https://github.com/PyCQA/flake8) and [Black](https://github.com/ambv/black/).

In the meantime, this works:

```sh
pyupgrade `find . -name "*.py"`
```

**Comment by asottile** [comment]
I'd suggest using [pre-commit](https://pre-commit.com) to run `pyupgrade` (or, well, any linter) -- pre-commit is better at running your linters than your linters could be because it knows about what is checked in and can identify extensionless executables.

Your "workaround" would be my other suggestion -- no need to make a tool more complicated than it needs to be if there's another tool which does exactly what you need.

Adding directory recursion is a surprising amount of complexity, you then need to handle exclusion, inclusion, globs, walking, ordering, and a bunch of other problems I'm not interested in solving (again) (because `pre-commit` does this better!).

**Comment by cdeil** [comment]
@asottile - thank you for this wonderful tool!

I would also find this option useful to pass a folder. Yes, it's a bit of code to walk the directories, but `black` has a very good implementation that would be copied.

It's not obvious to me why one would use `pre-commit` to upgrade a given codebase. Upgrading is a one-time action, at least that's how I want to use it. So why make this a pre-commit hook? -- @asottile maybe you could clarify a bit at the start of the readme.

**Comment by hugovk** [comment]
My workaround now also checks the found thing is a file (once `*.py` found a directory):

```sh
pyupgrade `find . -name "*.py" -type f`
```

**Comment by asottile** [comment]
It's not just a one time tool, it will continue to enforce the rewrites into the future (and gain features over time). You don't want to have to manually point out "this code base is python 3+ don't do X" in code reviews ad infinitum.

Even if you don't want to have hooks indefinitely, `pre-commit try-repo ... `  is good for one time runs

**Comment by bagerard** [comment]
Hi @asottile I understand that you are advocating for pre-commit but I believe it would be good to mention the trick with `pyupgrade `find . -name "*.py" -type f`` in a "Usage" section of the readme as well. What do you think?

**Comment by asottile** [comment]
that has some correctness and portability issues, slightly better is `find . -name '*.py' -exec pyupgrade {} +` or `find -name '*.py' -print0 | xargs pyupgrade`, `shopt -s globstar; pyupgrade **/*.py`, etc.

I don't really think it's the readme's place to teach how to use unix commands

**Comment by bagerard** [comment]
Alright that's your call :) Thanks for the quick feedback and for the library
