### ISSUE TITLE
f"wat".encode("utf-8") can also be rewritten to remove the encoding

### ISSUE THREAD

**Issue by asottile** [asottile/pyupgrade#483]
https://github.com/asottile/pyupgrade#encodeutf-8

**Comment by davidism** [comment]
I just noticed this changed Jinja and Werkzeug in a few places, but not everywhere that "utf-8" is specified. Common wisdom is that `.encode`, `open`, etc. should *always* be given an encoding when writing libraries because you don't know what `sys.get_default_encoding()` will be on the user's machine. I think the reasoning here is that since the source encoding is utf-8 and f-strings are literals, they are utf-8, but that doesn't change that `sys.get_default_encoding()` might not return "utf-8". Could you provide more information about why this change is safe?

**Comment by asottile** [comment]
you're confusing python's default encoding (always utf-8 since python 3) and python's default io encoding (platform dependent)

**Comment by davidism** [comment]
`str.encode()` doesn't default to the platform encoding?

**Comment by asottile** [comment]
correct it does not, always utf-8

**Comment by asottile** [comment]
(same for decode as well, but pyupgrade can't accurately detect all calls to encode and decode except for literals)

**Comment by davidism** [comment]
Wow, I had no idea! I've been operating under the assumption that everything except source files defaults to the platform encoding. Might be good to put an extra sentence in the readme about that upgrade, I have a feeling a lot of people will be surprised by that.
