### ISSUE TITLE
Feature Request: Exclude lines from conversion with a comment

### ISSUE THREAD

**Issue by CarliJoy** [asottile/pyupgrade#574]
It would be nice if line/block could be excluded from upgrading with a comment like ` # nopyupgrade`  or `# start nopyupgrade` in order to keep specific lines:
i.e. `dict(foo="bar")`  when intended.

We are discussion to include `pyupgrade`  in our teams pipeline but some team mate made this an requirement.

Would / Will this be possible in the future? 

Have a glimps look in the source I don't see how to introduce this easily :-/

Any thoughts?

**Comment by asottile** [comment]
no sorry, pyupgrade is an opinionated tool of you don't like the opinions don't use it

the whole point is that there's no discussions

**Comment by CarliJoy** [comment]
Understood. Thanks for the fast feedback :)

**Comment by JacobHayes** [comment]
I greatly appreciate the opinionated nature, but wonder if there might still be a valid use for this. For example, I'm working with code that explicitly inspects (user defined) type hints. In tests I confirm `tuple[int]` and `Tuple[int]` are both handled properly. I'd like for the rest of my code to use new hint syntax, but spot-disable in tests. Otherwise, running `pyupgrade` triggered a test failure + reduced coverage. `Tuple_ = globals()["Tuple"]` works as a questionable workaround (without having to ignore `tests/` completely). 😅

This seems a bit different than say `black` as there may be runtime observable differences that may need an escape hatch. However - if you still prefer this not be added, I can understand that too!

**Comment by asottile** [comment]
you're looking for `--keep-runtime-typing`
