### ISSUE TITLE
Incorrect rewrite of six.reraise with traceback as keyword argument

### ISSUE THREAD

**Issue by cjwatson** [asottile/pyupgrade#583]
Reduced from real code in Launchpad:

```
$ cat t.py
import sys

from six import reraise

exc_info = sys.exc_info()
reraise(exc_info[0], exc_info[1], tb=exc_info[2])
$ pyupgrade --py3-plus t.py
Rewriting t.py
$ cat t.py
import sys

from six import reraise

exc_info = sys.exc_info()
raise exc_info[1].with_traceback(None)
```

pyupgrade has missed the keyword argument here; this should instead be rewritten to `raise exc_info[1].with_traceback(exc_info[2])`.

(In fact in Python 3 this can end up just being a plain `raise`: the original code was more complicated and had a second possible exception being raised and handled between `sys.exc_info()` and `reraise()`, which in Python 2 would have caused plain `raise` to raise the second exception, but the exception scoping changes in Python 3 mean that a plain `raise` will do the right thing.  I don't expect pyupgrade to do that sort of analysis, though.)

**Comment by asottile** [comment]
it's falling into the reraise-2 choice: https://github.com/asottile/pyupgrade/blob/234e07160f1d6a171b1100de7046a92d4866e0ba/pyupgrade/_plugins/six_calls.py#L175-L180

presumably because named arguments were considered invalid and it is detecting your call as the 2-arg case

if you change your call to `reraise(*exc_info)` or `reraise(exc_info[0], exc_info[1], exc_info[2])` then pyupgrade will produce the correct call
