### ISSUE TITLE
Presence of future annotation import causes improper application of PEP 604 for Python 3.7

### ISSUE THREAD

**Issue by daneah** [asottile/pyupgrade#587]
Given these file contents:

```python
# foo.py

from __future__ import annotations

from typing import Optional


def some_function(some_arg: Optional[str] = None):
    ...
```

Running the following command:

```shell
$ pyupgrade --py37-plus
```

Rewrites the file contents to:

```python
# foo.py

from __future__ import annotations

from typing import Optional


def some_function(some_arg: str | None = None):
    ...
```

Which to my understanding is not valid before Python 3.10. Note that if the `from __future__ import annotations` line is not present initially, the file remains unchanged.

This is the case on at least versions `2.29.1` and `2.31.0`.

**Comment by MarcoGorelli** [comment]
> If the from __future__ import annotations line is not present initially, the file remains unchanged.

Yes, because `str | None` isn't valid if `from __future__ import annotations` isn't there

**Comment by daneah** [comment]
It isn't valid in Python 3.7 regardless, as to my understanding PEP 604 only becomes valid in Python 3.10. Am I misunderstanding?

**Comment by MarcoGorelli** [comment]
> It isn't valid in Python 3.7 regardless

it is valid if you have `from __future__ import annotations`:
```console
(venv37) marcogorelli@OVMG025 tmp % cat t.py 
# from __future__ import annotations
a: str | None
(venv37) marcogorelli@OVMG025 tmp % python3.7 t.py 
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    a: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(venv37) marcogorelli@OVMG025 tmp % vim t.py 
(venv37) marcogorelli@OVMG025 tmp % cat t.py 
from __future__ import annotations
a: str | None
(venv37) marcogorelli@OVMG025 tmp % python3.7 t.py
```

> I took these listed conditions to be ANDed together, but seems instead to behave as an OR currently.

That's right, it's OR. I think this was brought up before but the maintainer thought it was clear enough as it is

**Comment by daneah** [comment]
Okay, TIL that the `|`-based union syntax is allowable. Thanks for the context!

**Comment by thisch** [comment]
It's interesting that this is available in py3.7. I also wanted to open a `pyupgrade` issue about the same issue, because I was surprised that `pyupgrade` changes the annotations even though python 3.10 is explicitly mentioned in the header of PEP 604.  For PEP 585 I would have also expected that `a:  list[str] = []` works only starting with py3.9, but apparenetly it already works with python3.7. In the case of PEP 585 this is even mentioned in the text of the PEP, but this is not the case for PEP 604.

**Comment by Anthchirp** [comment]
While the syntax is _allowed_ it is not actually _supported_, future import or not.

Brief example:
```
>>> import sys; sys.version
'3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) \n[GCC 7.5.0]'
>>> a: str|None
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    a: str|None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
>>> from __future__ import annotations
>>> a: str|None
>>> __annotations__
{'a': 'str | None'}
```
vs
```
>>> import sys; sys.version
'3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:39:36) [GCC 9.4.0]'
>>> a: str|None
>>> __annotations__
{'a': str | None}
```

So therefore if you 
* support Python <3.10,
* use `from __future__ import annotations`, and
* either you (or your downstream code) uses `__annotations__`

then you must not use pyupgrade without `--keep-runtime-typing` otherwise you may change runtime behaviour.

Which is why I was surprised that this change is the default with eg. `--py37-plus`.

**Comment by asottile** [comment]
it is supported, just not in the uncommon case where your code uses runtime typing, therefore the flag `--keep-runtime-typing`

**Comment by Anthchirp** [comment]
Yes, supported in the sense that with the future import you can literally put anything there and it will be ignored.
```
>>> from __future__ import annotations
>>> x: hello-world
>>> __annotations__
{'x': 'hello - world'}
```

**Comment by asottile** [comment]
of course, but pyupgrade doesn't "put anything there", it puts things that type checkers understand

**Comment by Anthchirp** [comment]
Well, my point stands that with default settings pyupgrade changes runtime behaviour, breaking core-library function use, which I found unexpected. :shrug: 

Whether this is 'uncommon use' shouldn't matter - there are loads of core functions that I personally don't use, but that doesn't mean other people don't use them. Whether _my_ code uses runtime typing is also irrelevant, as I write libraries and I can't speak for anyone _using_ my code, and they would be affected by this change. Which is why I personally believe the default should be to leave this alone unless `--py310-plus` or eg. `--update-runtime-typing` is specified.

Your view may differ and I respect that. I can still use it with `--keep` as a one-off.

**Comment by asottile** [comment]
you don't respect it though, you're here making noise and telling people how to use the tool
