### ISSUE TITLE
f-string replacement for string concatenation with `+`

### ISSUE THREAD

**Issue by christianbundy** [asottile/pyupgrade#801]
## Preface

I've searched the issues and spent ~5 minutes looking for a duplicate, but haven't been able to find one. Apologies in advance if I've missed the thread, I know it's a waste of attention to have the same issue re-raised multiple times.

Keywords that I used, maybe useful for future searchers: f-string plus add `__add__ ` `__radd__` concat concatenate format +

## Problem

pyupgrade has had a great impact on code consistency, but one place I keep bumping into trouble is code like:

```python3
"hello " + name "!"
```

If this had been `"hello {}!".format(name)` then pyupgrade would've replaced with an f-string, but since it's concatenating string using `+` this isn't handled.

## Solution

I would like for pyupgrade to support this transformation. 

> this is out of scope, pyupgrade is only meant to "automatically upgrade syntax for newer versions of the language"

This is a great point. I'd like to present a brief history of how this syntax has looked in different versions of the language:

- Python 0.9.8: `"hello " + name + "!"`
- Python 0.9.9: `"hello %s!" % name`
- Python 2.6.0: `"hello {}!".format(name)`
- Python 3.6.0: `f"hello {name}!"`

(As far as I can tell, `"%s" % some_str` syntax was added in https://github.com/python/cpython/commit/e537240c252ff678d49451ee6f80fa934653a724 between v0.9.8 and v0.9.9, but I'd love to be corrected here if I've misunderstood.)

Admittedly, this is slightly tongue-in-cheek, and I'd like for pyupgrade to support this for pragmatic reasons, but I understand that clear scope is important and after too much `git bisect` I think it's clear that there was a previous version of the language without this syntax, and that an upgrade is relevant.

Please flame accordingly and have a great weekend.

**Comment by asottile** [comment]
concatenation is tricky because things can override `__radd__` and `__format__` so it's a little less safe than the `%` and `.format` upgrades

**Comment by violuke** [comment]
We would find this really useful, and understand the risks. Would it be possible to add this with a flag to enable it maybe? Thank you.

**Comment by ThiefMaster** [comment]
Maybe it could be behind a switch? For example, I know that my codebase doesn't do `__radd__` magic, so I could safely run pyupgrade with that switch turned on.

**Comment by asottile** [comment]
no thanks

**Comment by ThiefMaster** [comment]
"No thanks"? Really, that's all? Come on, I get that certain repetitive types of issues and questions are annoying for maintainers (being one for pallets I know that all too well), but this one is almost certainly none of those.

And how how else to solve it besides making it configurable? With `__radd__` also being not particularly common (unless you do weird math stuff or similarly obscure things I guess ;)), upgrading simple concatenation to f-strings unless opted-out seems like a good solution - especially since you usually cannot know the types of the object and I highly doubt you plan to take typing into account (even if it was way more popular in larger applications than it currently is)...

There's already `--keep-percent-format` as a precedent for making some things configurable as well - and in fact this switch is incredibly useful since I have some strings that contain LaTeX snippets, and with them using `{...}` a lot for other purposes than interpolating external data, converting from using `%s` those to f-strings or `.format()` (both requiring e.g. `\foo{{bar}}` which reduced readability) is not desirable, hence me using this switch.

**Comment by asottile** [comment]
I am not building and maintaining a tool that is option hell.  the current settings are for breakages only

please don't tell me how to run my project

**Comment by ThiefMaster** [comment]
replacing `'foo' + barobjectwithradd` with `f'foo{bar}'` in a codebase that has such objects wouldn't be breakage? ;)

anyway, not trying to tell you how to run your project, just tried to understand why you're so against adding it as an option

**Comment by violuke** [comment]
I'm surprised that this suggestion has caused such upset. Given that no appetite is there for this to be in pyupgrade, https://github.com/ikamensh/flynt might be helpful. I've not tried it out yet, but it looks promising.

I'm not sure closing as "Completed" is accurate though 😉

**Comment by asottile** [comment]
my project is also not an advertising space
