### ISSUE TITLE
Support for downgrades ?

### ISSUE THREAD

**Issue by dazza-codes** [asottile/pyupgrade#878]
Could pyupgrade possibly support downgrade operations?  In some circumstances, it could be useful to downgrade type hints.

I recently had a situation during a migration from python 3.8 to 3.10 where a deployment still on 3.8 would crash when we applied pyupgrade changes to typing for 3.10.  Although python claims the type hinting is not a runtime issue, it absolutely is a runtime issue if any 3.10 type hints are applied to 3.8 (they are not entirely ignored or backward compatible).

**Comment by asottile** [comment]
the tool is not called "pydowngrade" but you're free to write such a tool if you want to.

if you need runtime compatibility for type hints there is an option for that already (`--keep-runtime-typing`) though it's impossible to know what your actual problem was because you did a poor job of creating a bug report and did not describe your actual issue.

pyupgrade tries pretty hard to not break code and I suspect you either ran with `--py310-plus` (trust me, my code only runs on python 3.10 or above) or you utilized some sort of runtime type hinting (such as through `pydantic` or other libraries which abuse the type system) and didn't use the correct argument to pyupgrade
