### ISSUE TITLE
`Generator` type annotation wrongly shortened

### ISSUE THREAD

**Issue by david-zwicker** [asottile/pyupgrade#962]
`pyupgrade` turns the following code

```python
def f() -> Generator[float, None, None]:
    ...
```

into 

```python
def f() -> Generator[float]:
    ...
```

which is wrong according to `mypy`. I believe `pyupgrade` should keep the three-argument version.

**Comment by asottile** [comment]
you're on an old mypy

**Comment by david-zwicker** [comment]
I'm on `mypy 1.11.1 (compiled: yes)`, which I believe is the latest one.

**Comment by asottile** [comment]
show your output and full code?

**Comment by david-zwicker** [comment]
I cannot fully isolate the problem, but it appears in the code base of [`py-pde`](https://github.com/zwicker-group/py-pde). I'll try to come up with a minimal example and post it here!

**Comment by asottile** [comment]
please start with that next time instead of wasting my time!

**Comment by e-gebes** [comment]
I have the same or a similar issue. I ran `pyupgrade --py310-plus myfile.py` on the following code

```python
from __future__ import annotations

from collections.abc import Generator


def generator() -> Generator[int, None, None]:
    yield 1
```
and it gets shortened to:

```python
from __future__ import annotations

from collections.abc import Generator


def generator() -> Generator[int]:
    yield 1
```
My version of pyupgrade is 3.17.0

*Without* the `from __future__ import annotations` line the Generator type hint is *not* shortened.

I think

* the shortening should not depend on that future import
* the shortening should be done for Python 3.13 code only, and not when run with the `--py310-plus` flag. The CPython docs mention the possibility for shortening only since Python 3.13: [link](https://docs.python.org/3.13/library/typing.html#typing.Generator). The current mypy stable (1.11.2) docs do not mention the shortening: [link](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#generators), also not the [typing documentation](https://typing.readthedocs.io/en/latest/spec/annotations.html#annotating-generator-functions-and-coroutines) (as of now).

**Comment by asottile** [comment]
you're wrong.  mypy accepts it just fine with the import just like all other improvements.

where are you seeing otherwise?

**Comment by e-gebes** [comment]
it's irrelevant if a code optimization works with one specific tool
read the CPython doc!

it's legitimate to write Python 3.10 code, it's legitimate to write 3.10 code with the *annotations* import, and it's legitimate to write the type hints in the same 3.10-way

when I run `pyupgrade --py310-plus` apparently the "3.10 type hints" are upgraded to 3.13 type hints (!), which is surprising behavior - it'd be better to change that

at least the behavior is somehow documented: https://github.com/asottile/pyupgrade?tab=readme-ov-file#pep-696-typevar-defaults
and there's remedy with `--keep-runtime-typing` in this case

**Comment by asottile** [comment]
read the pyupgrade doc!

you still haven't demonstrated any breakage so I'm assuming you're just a troll
